apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: my-notebook 
spec:
  selector:
   workloadSelector:
     matchLabels: {
       app: notebook
     }
  appInfo:
    purpose: Fraud Detection
    role: Data Owner
  data:
    - dataSetID: "fybrik-notebook-sample/medals-winners"
      requirements:
        interface:
          protocol: s3
          dataformat: csv
    - dataSetID: "fybrik-notebook-sample/bank"
      requirements:
        interface:
          protocol: s3
          dataformat: csv
