  
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: hello-world-read-module
  labels:
    name: hello-world-read-module
    version: 0.0.1  # semantic version
  namespace: fybrik-system
spec:
  type: service
  chart:
    name: ghcr.io/fybrik/hello-world-read-module-chart:0.0.0-main
    values:
      image.tag: main
  capabilities:
    - capability: read
      scope: workload
      actions:
        - name: RedactAction
        - name: RemoveAction
      api:
        endpoint:
          port: 80
          scheme: grpc
        protocol: s3
        dataformat: csv
      supportedInterfaces:
        - source:
            protocol: s3
            dataformat: parquet
        - source:
            protocol: s3
            dataformat: csv
  statusIndicators:
    - kind: hello-world-read-module
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error
