  
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: hello-world-read-module
  labels:
    name: hello-world-read-module
    version: 0.0.1  # semantic version
  namespace: fybrik-system
spec:
  type: service
  chart:
    name: ghcr.io/fybrik/hello-world-read-module-chart:0.0.0-main
    values:
      image.tag: main
  capabilities:
    - capability: read
      scope: workload
      api:
        connection:
          name: rest
          rest:
            endpoint: "https://{{ .Release.Name }}.{{ .Release.Namespace }}:80/readAsset"
      supportedInterfaces:
        - source:
            protocol: s3
            dataformat: parquet
        - source:
            protocol: s3
            dataformat: csv
      actions:
        - name: RedactAction
        - name: RemoveAction
  statusIndicators:
    - kind: hello-world-read-module
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error
