name: Test
on: pull_request
jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        version: v3.6.3
    - uses: azure/setup-kubectl@v2.0
      id: install
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.5.0
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
    - name: run-test
      run: ./test-script/test_module.sh kind19 0.6.0 0.6.0
